version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "${PORT_BE}:${PORT_BE}"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: bash -c "npm run migrate:dev && npm run seed && npm run start:dev"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT_BE}/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "${PORT_FE}:${PORT_FE}"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT_FE} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
