version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
      POSTGRES_DB: exampledb
    ports:
      - "6000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
